### ISSUE TITLE
Bold

### ISSUE THREAD

**Issue by fredck** [ckeditor/editor-recommendations#1]
Bold seams to be one of the must have features because of its historical use in editing. There are many variations of this feature though and HTML5 introduced new semantic aspects around it.

**Comment by fredck** [comment]
If this feature would be ever included, an initial proposal is already available for discussion:
http://ckeditor.github.io/editor-recommendations/features/bold.html

**Comment by Comandeer** [comment]
In case of "Bold" feature everything seems to be pretty clear. `strong` is just an "industry standard".

But to be fair ;) There are generally two options that could be used for "Bold" feature:
- [`strong` element](http://www.w3.org/TR/html5/text-level-semantics.html#the-strong-element) - the de facto standard for "Bold"; it indicates that some part of content has a greater importance than other.
- [`b` element](http://www.w3.org/TR/html5/text-level-semantics.html#the-b-element) - the "old standard" from pre-POSH era; it just visually distinguish some part of content

"Bold" is used mainly to mark important parts of text, so `strong` is a clear winner. But… there are some cases in which `strong` is not appropiate, e.g. marking word being defined in its definition. Users tend to use "Bold" feature here just because they want that word to be bold. It's one of that situations where what you get is not exactly what you mean, but that use case of this feature is probably rare.

There are also some issues with i18n, e.g. keystrokes are optimized for English language and it may be considered to optimize them for different languages.

**Comment by Comandeer** [comment]
Some stats. I've checked [22 editors](https://gist.github.com/Comandeer/623b317e09af53c75e46) to see how they implement some basic features.

"Bold" feature is present in all tested editors:
- 9 of them use `strong`
- 12 of them use `b`
- 1 uses own syntax, based on XML (`text:span`)

**Comment by Comandeer** [comment]
It's funny, but I've just realised that we fell into a trap with "Bold" feature ;)

All of our specs use Markdown's ""Bold" feature" to mark features' names. According to the "industry standard" that "Bold" also uses `strong` element. And that's wrong…

According to the HTML5 spec, `strong` should be used only to mark parts of text with great importance. Feature's name is not so important - it's terminology. We use "Bold" rather to visually distinguish it from other content. And it's the ideal example of how `b` should be used:

> The b element represents a span of text to which attention is being drawn for utilitarian purposes without conveying any extra importance and with no implication of an alternate voice or mood, such as **key words in a document abstract**, product names in a review, actionable words in interactive text-driven software, or an article lede.

It's the thing that I've already mentioned in this discussion, but now I have a live example ;)

**Comment by Comandeer** [comment]
Ok, it seems like a stable feature. I propose moving it from draft to the recommendation status. I'll wait 3 days for objections and then do what should be done ;)
