### ISSUE TITLE
Superscript and subscript

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#5]
The "Superscript" can be useful in mathematical equation and to create references in text. I don't think it's a must have, but it's certainly nice to have.

There are mainly two options for "Superscript" to be considered:
- [`sup` element](http://www.w3.org/TR/html5/text-level-semantics.html#the-sup-element) - note that spec generally **discourage** to use that element if there are other options
- [superscript Unicode characters](http://www.w3.org/TR/unicode-xml/#Superscripts) - I think that option has limited use cases

---

Honestly I can't think of any use cases for subscript, except mathematical equations, so it's even less useful than "Superscript" feature

There are mainly two options for "Subscript" to be considered:
- [`sub` element](http://www.w3.org/TR/html5/text-level-semantics.html#the-sub-element) - note that spec generally **discourage** to use that element if there are other options
- [subscript Unicode characters](http://www.w3.org/TR/unicode-xml/#Superscripts) - I think that option has limited use cases and support

**Comment by fredck** [comment]
Note that, when it comes to the Unicode option, this is not supposed to be a spec feature, but it is instead a simply typing feature. In other words, users are in any case able to input any Unicode character, even outside of the Superscript range. So this doesn't seam to be a problem to be solved by an editor toolbar button, which in any case would be limited, because not everything is available in Unicode.

Another point is that both `sub` and Unicode characters bring "zero" semantical value to the content. That's because they don't help understanding what the "superscript" is about. For example, it'll not helping understand the meaning it has in x<sup>2</sup> (exponent) and how different it is from 1<sup>st</sup> (meaningless style).

IMHO, this feature should not be included as it has simply visual use which should be solved by other means (Unicode typing or automatic text transformation).

**Comment by Comandeer** [comment]
> Note that, when it comes to the Unicode option, this is not supposed to be a spec feature, but it is instead a simply typing feature.

Yes, that's right.

> Another point is that both sub and Unicode characters bring "zero" semantical value to the content.

[HTML5 spec](http://www.w3.org/TR/html5/text-level-semantics.html#the-sup-element) is somehow against it:

> These elements must be used only to mark up typographical conventions with specific meanings, not for typographical presentation for presentation's sake.

The problem here is fact that generic `sup` element is just not conforming to the standard, because it would really exist just for presentation's sake. In other elements, such as `i` or `b`, spec suggest using  microformats to indicate use case for the element:

``` html
<p>The <i class="taxonomy">Felis silvestris catus</i> is cute.</p>
```

It may be the remedium for our "presentation's sake problem", but it also renders generic "Superscript" feature completely useless, because in that case superscript should be included as a part of other features (eg. references).

So yes, I'm also against adding this feature.

**Comment by Comandeer** [comment]
I joined "Superscript" and "Subscript" (#6) issues, because nearly every comment about one of them would also apply to the second. Even HTML5 spec join them together, so it shouldn't be a problem ;)

**Comment by Comandeer** [comment]
Some stats. I've checked [22 editors](https://gist.github.com/Comandeer/623b317e09af53c75e46) to see how they implement some basic features.

"Superscript/subscript" is present in 8 editors, all of them implements it as `sup`/`sub`.

**Comment by Comandeer** [comment]
Ok, it seems like a feature that is not really needed. I propose to just remove the draft. I'll wait 3 days for objections and then do what should be done ;)
