### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by jodator** [ckeditor/editor-recommendations#61]
As a foreword: I know that setting font size is not a best feature to add as it should be preferably set by webpage CSS. But such feature might be required for other use-cases.

I'd like to propose a new feature to be defined: Font size that will control size of a text.

Note: This feature might not go as part of any of existing use-cases.

**Comment by scofalik** [comment]
My question would be how semantic do we want to be with this kind of feature? I guess there are two roads to go:
1. Just use `style` attribute. Define a list of styles and names for them. This way the developer responsible for integration may decide whether they want to enable `px` or `em`s.
2. Go with `class`es. Similarly, a list may be introduced, linking a label with a name. Instead of applying `font-size` to `span`, a `class` would be applied. This way we can provide some classes configured by default and then left the decision how they are displayed to the webpage developer. For example, we might go with "extra large, large, normal, small, smallest". This has additional upside of the possibility of being rendered differently in different context, for example, in heading large font might be declared as `h2 .font-large { font-size: 30px; }` while in normal text as `.font-large { font-size: 20px; }`.

**Comment by Comandeer** [comment]
Such presentational-only features goes against [ER's general polices](http://ckeditor.github.io/editor-recommendations/general-policies/) as they don't have any semantic value. Therefore I don't think that they should be included into ER.

**Comment by balunaidu** [comment]
font-size implementaion for thirdparty ui

**Comment by balunaidu** [comment]
how to do that?
