### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by jodator** [ckeditor/editor-recommendations#63]
Similar to [font background color](https://github.com/ckeditor/editor-recommendations/issues/62) but with more semantic meaning.

The highlight feature is inspired by highlighting a text on paper with a marker pen. As such the approach in implementing this in HTML code might be different. I image this as applying a defined CSS class to a text that later might be styled depending on a web-page theme.

Rather then adding a background color to a text the highlight feature would rather mark this text with a meaning like "important" or "check with legal department". The visual style of such highlight must be also defined.

**Comment by Comandeer** [comment]
There is dedicated HTML element for such use cases: [`mark`](http://w3c.github.io/html/textlevel-semantics.html#the-mark-element).

**Comment by fredck** [comment]
The `<mark>` element fits perfectly to this case. This is how Chrome styles it by default:

![image](https://user-images.githubusercontent.com/630060/32176275-7f5a38e2-bd87-11e7-9758-cc83df2dc835.png)

**Comment by jodator** [comment]
The same on Firefox: 
![selection_023](https://user-images.githubusercontent.com/247363/32177117-b233efea-bd89-11e7-82f3-0a6f179b34db.png)

**Comment by Comandeer** [comment]
Added [draft](http://ckeditor.github.io/editor-recommendations/features/highlight.html) for this feature in eac4d80.

**Comment by duracell80** [comment]
In HTML4 this must be done with a class and not an inline style. This is because of accessibility. The editor should not override user stylesheet settings particularly not for background colors of text.

In HTML 5 ... < mark >highlighted text here< / mark > should take the browser default, we should not demand yellow.
https://www.w3schools.com/tags/tag_mark.asp

Users can then style this how they need it to be styled to keep it readable for them, the editor shouldn't assume highlighted text must always be yellow. White text on a black background should always be the first high contrast option, though I know from experience black text on yellow is what project contributors will want to see.

```
mark {
    background-color: yellow;
    color: black;
}
```

https://www.boia.org/blog/the-most-common-web-accessibility-issues-to-avoid

Color. Colors should not be used to convey meaning. If developers wish to use colors to communicate something meaningful, alternative options should also be provided to communicate the meaning. This applies to features such as highlighted text.

With this example ... the green is hard to read, if dark background the text must be white

![low-constrast](https://user-images.githubusercontent.com/18121278/40324754-2385b4a2-5cff-11e8-8211-57f66d296f55.JPG)

**Comment by duracell80** [comment]
Add "high contrast" as a marker (white text on black bg)

![add-high-contrast-options](https://user-images.githubusercontent.com/18121278/40324828-5ca26906-5cff-11e8-882e-14fae6627f3f.JPG)

**Comment by Comandeer** [comment]
@duracell80 it seems that you are missing feature in CKEditor 5. In that case, please [report a feature request](https://github.com/ckeditor/ckeditor5/issues/new).

**Comment by duracell80** [comment]
Done, I don't think this feature currently is "fully accessible". The green marker in particular.

**Comment by Comandeer** [comment]
Ok, it seems like a stable feature. I propose moving it from draft to the recommendation status. I'll wait 3 days for objections and then mark it as recommendation.
